# Configuração do Admin Provisório
sistema.admin.email=admin@senai.com
sistema.admin.senha=admin123

# JWT / Spring Security
security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=600
security.jwt.access-exp-min=15
security.jwt.refresh-exp-days=7

# MQTT SSL
mqtt.broker-url=ssl://meu-broker:8883
javax.net.ssl.trustStore=classpath:meu_truststore.jks
javax.net.ssl.trustStorePassword=minhasenha
javax.net.ssl.trustStoreType=JKS