spring.profiles.active=prod

spring.application.name=MetroAcesso

# ===============================
# Configuração JWT (exemplo)
# ===============================
# ${JWT_SECRET}
security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=28800

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=ERROR
spring.jackson.time-zone=America/Sao_Paulo

# ===============================
# Configuração do Admin Provisório
# ===============================
sistema.admin.email=admin@metroacesso.com
sistema.admin.senha=admin123