spring.application.name=MetroAcesso
spring.flyway.enabled=false

# ===============================
# Banco de dados (H2 - LOCAL)
# ===============================
spring.datasource.url=jdbc:h2:mem:metro_acesso
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT / Spring Security
# ===============================
security.jwt.secret=mysupersecretkeymysupersecretkey123!
security.jwt.expiration=600
security.jwt.access-exp-min=15
security.jwt.refresh-exp-days=7

# ===============================
# Admin provisório (fixo local)
# ===============================
sistema.admin.email=admin@local.com
sistema.admin.senha=123456

# ===============================
# CORS / URL local
# ===============================
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
app.public-base-url=http://localhost:8080

# ===============================
# MQTT local
# ===============================
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=app-local
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1

# ===============================
# Servidor
# ===============================
server.address=0.0.0.0
server.port=8080